### ISSUE TITLE
Bring all good PRs from main repo

### ISSUE THREAD

**Issue by soroshsabz** [Havunen/DotSwashbuckle#1]
ITNOA

hi,

Please review all PRs in [main repo](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pulls?page=1&q=is%3Apr+is%3Aopen) and bring all good of them to this repo to resolve many bugs and needed features

thanks a lot

**Comment by Havunen** [comment]
Yeah I went through some of them,

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2730

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2742/files

 is there some particular PR which you are interested

**Comment by schnerring** [comment]
I created https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2671 adding support for System.Text.Json polymorphism.

Good luck with the PR. Any reason why you didn't fork the repo to preserve its commit history?

**Comment by Havunen** [comment]
> Good luck with the fork! Any reason why you didn't use the GitHub fork button to preserve its commit history?

Because I already had a fork I didnt want to delete it

**Comment by cmenzi** [comment]
Question is if we should not switch to [NSwag](https://github.com/RicoSuter/NSwag) and make this as the default.

**Comment by Havunen** [comment]
> I created https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2671 adding support for System.Text.Json polymorphism.

This is now ported here, thanks @schnerring  ref https://github.com/Havunen/DotSwashbuckle/commit/58976ef58b1c9ff195ff38d73c5eb15118de862d

I also fixed performance bug in XML comments which caused the generation to be very slow

I am planning to remove all obsolete fields, update release notes and release v2

**Comment by Havunen** [comment]
v2.0.0 released

**Comment by Havunen** [comment]
I have went through the following PRs. 
✅ means the following changes are already ported or implemented in this branch. 
⛔ means I would not merge the PR as is.

2023 list:

- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2746 ✅ 
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2742 ✅ 
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2736 (skipped, this is .NET 8 only already)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2730 ✅ 
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2727 (skipped, this fork has XML comments logic rewritten)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2726 ✅ , also everything else in the CLI process is now invariant culture based
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2724 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2723 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2720 (I believe this is wrong, I commented the PR and asked for more info)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2718 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2715 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2714 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2713 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2710 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2705 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2704 (this possibly needs some polishing, need to go through it later)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2697 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2695 (tests need to be written)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2694 ⛔ 
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2687 (looks good, but XML comment handling is changed in this fork so the PR needs to be redone)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2685 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2683 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2682 ⛔ its about old frameworks which this fork is not going to support
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2677 ( not sure, need to go through it later, issue seems legit tho )
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2672 ⛔ its about old frameworks which this fork is not going to support
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2671 ✅ 
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2663 (looks wrong, commented)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2644 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2635 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2621 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2619  ⛔  ( I will update ReDoc and SwaggerUI manually )
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2615 ( need to go through it later )
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2610 ( commented, otherwise looks good to me )
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2591 ( duplicate )
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2590 ( looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2581 ⛔ I will update those front ends myself manually
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2569 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2672 ⛔ this is .NET 8 and forward only

**Comment by Havunen** [comment]
2022 list:

- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2565 (looks good, minor changes needed due to changes in this fork)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2546 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2540 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2533 (looks good, inc. @jamesmcroft s comments)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2532 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2524 (look good partially, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2522 (looks good, will merge)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2515 ✅ 
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2502 ⛔- irrelevant changes to this fork 
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2493 (looks good, but need to revisit open api docs and the changes later)
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2473 ( issue is legit, not sure about the fix, need to revisit this later )
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2472 ( looks good, but need to revisit this later )
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2464 ⛔ 


To be continued later

**Comment by Havunen** [comment]
If anybody is interested helping to get all these fixes in. You can port the PR to this fork from any of the PRs which I have marked as (looks good, will merge) and I will merge it and release the changes to Nuget.

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2493 this can be work around by defining two methods so I am not porting it

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2522 I'm skipping this unless the work continues for GeneratePaths concurrent execution. Separate issue can be opened to this repository if interested about it.

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2533 lets check later if there is actually need for this

**Comment by jamesmcroft** [comment]
> * [Added support for enums when a JsonSerializerContext is used domaindrivendev/Swashbuckle.AspNetCore#2723](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2723)  🟡  (looks good, will merge, need to check if usage of dynamic could be avoided)

@Havunen to pull from my issue on the main repo: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2426

This is useful for scenarios where tools that injest large Swagger JSON files have limits on the number of reference types that are acceptable, e.g. Microsoft's Power Automate solution. This inline option, while making the Swagger JSON larger, enables support. 

The PR in reference is a copy of my original changes here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2427/files

The one that is currently open is missing a key feature whereby objects with properties that are self referencing will not be serialized correctly inline. In the PR, I have requested these changes.

I would be happy to bring this over.

**Comment by Havunen** [comment]
> > * [Added support for enums when a JsonSerializerContext is used domaindrivendev/Swashbuckle.AspNetCore#2723](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2723)  🟡  (looks good, will merge, need to check if usage of dynamic could be avoided)
> 
> @Havunen to pull from my issue on the main repo: [domaindrivendev/Swashbuckle.AspNetCore#2426](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2426)
> 
> This is useful for scenarios where tools that injest large Swagger JSON files have limits on the number of reference types that are acceptable, e.g. Microsoft's Power Automate solution. This inline option, while making the Swagger JSON larger, enables support.
> 
> The PR in reference is a copy of my original changes here: [domaindrivendev/Swashbuckle.AspNetCore#2427](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2427)
> 
> The one that is currently open is missing a key feature whereby objects with properties that are self referencing will not be serialized correctly inline. In the PR, I have requested these changes.
> 
> I would be happy to bring this over.

Sounds good to me

**Comment by Havunen** [comment]
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2683 🟡 ( was more complex than I thought, tests started failing etc. the change can be ported over if somebody is interested to do it )

**Comment by Havunen** [comment]
I have ported all the changes which I was able to do in this short period of time. All the merged changes are now available in the version 3.0.0. I consider this task now done, lets continue remaining tasks on separate issues.

https://www.nuget.org/packages/DotSwashbuckle.AspNetCore
https://github.com/Havunen/DotSwashbuckle/releases/tag/v3.0.0

**Comment by soroshsabz** [comment]
thanks :)

**Comment by soroshsabz** [comment]
@Havunen So I think we have to make PR from this repo to main repo, to see accumulative changes from main repo
